### PR TITLE
rebase of @doj 's sourceforge patch that adds test duration 

### PR DESCRIPTION
**Pull request by matthargett**
in millieconds to reporters.  only added the POSIX bits since I don't have Windows machine readily available to test and have no space on my dev machine to copy over a Windows dev VM. Some minor structural changes versus his approach. Open question: why can't we store the runtime for each test in its struct and then add up the test runtimes in finish_suite?

The integration tests that compare golden output files will also need to be changed/loosened to overlook the specific millisecond values.

### CODE REVIEW

**Comment by thoni56** [comment]
Totally agree with your open question. Especially since the solution in this PR breaks reporter API (as described in the docs) and forces the caller to manage the time info. Timing seems like an internal matter for the reporter, if possible.

**Comment by doj** [comment]
On Windows you want to use "DWORD timeGetTime(void);" see https://msdn.microsoft.com/en-us/library/windows/desktop/dd757629%28v=vs.85%29.aspx

The question on which layer of the code, should the test execution time be measured is a pure style question. I've opted for a solution at the core cgreen level, where the framework provides this value to the reporters. This requires changes to the reporter API. You can alternatively implement it as an internal details of each reporter. But it can lead to different solutions in the reporter implementations, and worse if reporters use different system calls to get time values, may lead to different reported runtimes for the same test when using different reporters.

Personally this was a patch I created, for a subsequent patch in which the XML reporter used the execution times to enhance the JUnit XML reporting.

Any of the two solution can be made to work, I've choosen this one as the single source of timing information created by the framework and presented to the reporters. If the cgreen-devs prefer the other solutions it will not harm my feelings. My use case was to provide time information for the XML reporter.

**Comment by thoni56** [comment]
@doj no offense intended, of course. And I agree that which solution you prefer is a matter of taste and style. Also I think the Ant/Jenkins/JUnit XML reporting timing info is a valuable addition.

My thinking went along the lines of "the reporter infrastructure should be responsible for it" rather than the individual reporters. I don't have a suggestion for implementation of that aspect right now (there's no AspectC, is there ;-)

**Comment by thoni56** [comment]
Actually there is an [AspectC](http://www.aspectc.com/)...

What I was thinking was probably bigger that this specific PR. Also factoring in dynamic loading of reporters. Giving the reporter infrastructure "class" more responsibility than being a patter for reporters.

One way of handling this would be to modify the reporter infrastructure so that the runner would always call the reporter "super class". Instead of calling the delegated, specific reporter functions directly through the pointers like

    (*reporter->start_suite)(reporter, ...

it would do

    start_suite(reporter, ...

which would do something like

    void start_suite(TestReporter *reporter, ... {
        // Do timing magic...
        (*reporter->start_suite)(reporter, ...
        ...
    }

thus allowing the reporter infra-structure to intervene and do common stuff.

This semi-new reporter layer could then also handle the responsibility of dynamically loading reporters.

**Comment by matthargett** [comment]
I like this idea a lot. Since it would be easy to forget/misuse, we would probably want to have a flag in the reporter struct that gets set when the top-level reporter's start() is called so the framework can output and error message when reporter->start() is called without having called the top-level reporter's start_suite(). comments?

**Comment by thoni56** [comment]
Moving this idea to #33.

In the mean time I can only see two ways to propagate to the specialized reporters:

1. add a parameter giving the timing
2. add the timing to the test structure, but then that structure has to be passed to the reporter

So, for now I can't see a way to *not* change the reporter extension API. Then this is as good a way as the other.

Any other ideas?

**Pull request merged**
