### PR TITLE
Improved handling of double

### PR DESCRIPTION
**Pull request by ykaliuta**
Could you check the minor fixes:

Yauheni Kaliuta (3):
      constraint.c: fix error output format for double
      assertions.c: decorate assert_that_double error output
      user api: install and include boxed_double.h

### CODE REVIEW

**Comment by thoni56** [comment]
Could you see if you could add some tests for this, please?

**Comment by ykaliuta** [comment]
Hi!

On Wed, Sep 2, 2015 at 9:05 AM, Thomas Nilsson <notifications@github.com> wrote:
>
> Could you see if you could add some tests for this, please?
>

Sure, I'll have a look.

**Comment by d-meiser** [comment]
While working on #4 I added a test for the double formatting. It's broken out into a separate commit:

1d6e4b9e29f306f0cd7b62296119dec95e22823e

Feel free to cherry pick onto this branch. @thoni56 is any additional testing needed before this branch can be merged?

**Comment by thoni56** [comment]
How do I cherry pick onto this pull request? How do I reference it?

**Comment by d-meiser** [comment]
@thoni56 as far as I know there is no way to cherry pick via github's web interface. Perhaps somebody with more github expertise can correct me if I'm wrong.

The only way I know to do this is in a local repo with the command line interface. I've opened PR #15 where I did that. The authorship and commit messages of the original commits are preserved. Feel free to close that PR if it's not ready for merging yet. @ykaliuta won't be able to amend that branch so it's easier for @ykaliuta to cherry pick onto her/his own branch to maintain this pull request in that case.

In case you're interested here are the steps I used to create the branch for PR #15:

```
# Get the for-upstream branch from ykaliuta's repo:
git remote add ykaliuta-cgreen https://github.com/ykaliuta/cgreen
git fetch ykaliuta-cgreen 
git checkout for-upstream
# Identify the commit to cherry pick:
git log master..add-is_less_than_double
git show 1d6e4b9e29
git cherry-pick 1d6e4b9e29
# Push to my github repo
git push origin for-upstream 
```

**Comment by ykaliuta** [comment]
Hi!

I rebased the stuff and can send another pull request if it's needed.


Shame on me, I'm not familiar enough with CMake and didn't find time, so
didn't play with testing the changes as I promised.

**Comment by thoni56** [comment]
Thanks, @ykaliuta for doing the main work. I used @d-meiser merge request and am closing this one.

**Pull request closed without merging**
