### PR TITLE
Added basic cmake package generation and install steps to build process.

### PR DESCRIPTION
**Pull request by snewt**
As a user I wanted to use `find_package( cgreen )` in a project's
CMakeLists.txt file and check that `cgreen_FOUND` variable is set.

The tooling used is based on CMake documentation [here](https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html) and the [forexample/package-example repositiory](https://github.com/forexample/package-example)

### CODE REVIEW

**Comment by snewt** [comment]
Looks like the build failed on a failure to find `CMakePackageConfigHelpers` which is documented in the 3.0.2 docs but the project currently only requires 2.6.

**Comment by snewt** [comment]
There are definitely alternative approaches! It might be that they'd require a smaller version bump ( looks like to 2.8).

**Comment by d-meiser** [comment]
What do the generated cmake files look like? Could we just add them to the source tree and install from there? That way you wouldn't need to bump the cmake version.

**Comment by snewt** [comment]
Revised cmake package config approach.

New package configuration and version configuration files.
Hopefully much more intuitive for additions in the future.

Removed need for CMakePackageConfigHelpers by simplifying package.

Still generating config.cmake files from config.cmake.in files
so that as a developer, variables set/used in the project's
CMakelists.txt can be accessed in the config files and don't
need to be maintained / hard coded in the config files.

The only place the above feature is really used at the moment
are to generate version config using the APPLICATION_VERSION
variable.

To test the functionality I attempted to build the project with
mulitple versions of cmake. Before the changes this PR reflects
were implemented, I was unable to successfully configure the
project on a version less than the 2.8.5. The revsion to
cmake_minimum_required version reflets the result of those tests,
not a requirement for the proposed features.

-- cmake version 2.6-patch 0 --
Error on:
if (NOT(CMAKE_MAJOR_VERSION LESS 3) AND APPLE)
  if(POLICY CMP0042)
    cmake_policy(SET CMP0042 NEW) # CMake 3.0 to use @rpath on MacOSX
libraries
  endif()
endif()

Error on:
include(GNUInstallDirs)

-- cmake version 2.6-patch 4 --

Error on:
include(GNUInstallDirs)

-- cmake version 2.8.0 --

Error on:
include(GNUInstallDirs)

-- cmake version 2.8.4 --

Error on:
include(GNUInstallDirs)

-- cmake version 2.8.5 --
Success

**Comment by d-meiser** [comment]
Overall I think this is a great addition. In my opinion it's a good idea to bump the minimum cmake version to 2.8.5 but others will have to make that call.

**Comment by thoni56** [comment]
Good work! In general we should be careful to bump CMake version requirements since we don't really know what's out there. I know @matthargett worked, or knew of someone working, in an environment where a very old CMake version was used.

However, as you have shown, it still would not work given the errors you got.

I'll have a look at this in the weekend, unless someone else want to take a stab at verifying it? @gardenia ? We want to still access CMake settings for the project in the normal CMake fashion, but that's pretty much it, I think.

**Comment by snewt** [comment]
@thoni56 @d-meiser thanks for taking a look! I'm a huge fan of your tool!

**Comment by gardenia** [comment]
FWIW I think setting a minimum cmake version of 2.8.5 is fine.  on Ubuntu 12.04 (for example) the version of cmake is 2.8.7 so that means it would still compatibile with the last 3 LTS versions.

**Comment by d-meiser** [comment]
@thoni56 in general I agree that it is a good idea to keep version requirements to a minimum. I think in this case it's not a huge deal because the version bump affects only cgreen *developers*. Cgreen *users* are free to use whatever version of cmake they want (including no cmake at all).

**Comment by thoni56** [comment]
Agreed. Wasn't putting this down, just making a note of the principle.

Since there are no distributions that have *Cgreen* and there are few pre-built binaries, more often than not, you, as a "user", will have to build *Cgreen* yourself. Which is not only a bad thing. One other unittest framework, forget which, made the decision to not publish pre-built binaries since most projects will have their own particular compiler settings.

This makes almost everyone a "developer" in this respect. (Wish that was not so, but there we are.) So more people are affected than we really would like.

Only way around *that* is to get *Cgreen* into some major distribution. That would at least help those "content" with a "standard" compiler setting. Also a 32- & 64-bit build (#94) will make this more possible.

**Comment by thoni56** [comment]
BTW, is there some documentation we should put in place for this?

**Comment by snewt** [comment]
@thoni56 I'll add some description to the repo's README.md and propose the additions in a PR on Monday.

**Pull request merged**
