### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by d-meiser**
This pull request adds a simple configuration for travis continuous integration testing. The test matrix contains shared and static builds with clang and gcc. See https://travis-ci.org/d-meiser/cgreen/builds/78221792 for an example.

The cgreen-devs organization will have to enable the cgreen repo for testing on the travis ci website for this to work. The link for the build status in the readme is dead now but should work as soon as the first test build for cgreen-devs/cgreen has completed.

### CODE REVIEW

**Comment by d-meiser** [comment]
Hi @thoni56 , thanks for merging the PR. Note that you'll need to enable testing on the travis ci website for the tests to work. Cheers, Dominic

**Comment by thoni56** [comment]
Yes, I got that, just haven't gotten around to it yet.

**Comment by thoni56** [comment]
Enabled, so let's trigger a build, ok to test.

**Comment by thoni56** [comment]
Done, and works: https://travis-ci.org/cgreen-devs/cgreen

**Comment by thoni56** [comment]
@d-meiser How did you manage to get travis builds for your local work? Cloned the repo under your user and added it to your Travis user?

**Comment by d-meiser** [comment]
@thoni56 correct, that should work.

Note that it's not strictly local. It's still on github but for my fork.

**Pull request merged**
