### PR TITLE
Cmake package documentation and version revision

### PR DESCRIPTION
**Pull request by snewt**
Added documentation to README.md and revised package version logic.

README.md provides brief explanation of what's available to you
as a user when using `find_package( cgreen )`.

In the process of validating what was described in README.md,
a fix was added to the cgreen-config-verion.cmake.in.
The file name was non-standard and the versoin's "beta" indication
needed to be omitted for `find_package` compatibility.

### CODE REVIEW

**Comment by d-meiser** [comment]
Would it make sense to squash these commits?

**Comment by snewt** [comment]
@d-meiser can do! commits squashed!

**Comment by thoni56** [comment]
Thanks. The only thing I feel is a down-side is the removal of "beta". I can see that it is not compatible with `CMake` package versioning.

Is there another strategy we can use to make it visible that the `Cgreen` you have is not from an official release?

**Comment by thoni56** [comment]
I think I misinterpreted the version marking issue. It's just the package handling that's affected and thus the names of the libraries. The version marking in the CMake-files can, and is, still announcing "beta". That's good.

Maybe we should look for a way to find out if the build is from a tag and then just use the tag name, or skip the beta-marking in an effort to remove a manual step when building release binaries.

**Comment by d-meiser** [comment]
> Maybe we should look for a way to find out if the build is from a tag and then just use the tag name...

This can be done with `git describe` (https://git-scm.com/docs/git-describe).

**Comment by thoni56** [comment]
Good idea, but I'm thinking that it would not work without additional logic from a source bundle, or would it?. We could possible store the output from `git describe` in a file if we are in a git tree and use that.

The logic of this need to go into the CMake-files and would trigger larger rebuilds than necessary whenever you have committed something.

What do other people do? Google has no quick answer...

**Pull request merged**
