### PR TITLE
text-reporter:  Only report summary from top-level suite.

### PR DESCRIPTION
**Pull request by tboese**
Prior to this change, if one create a top-level suite called Suite_A, and in
that suite added 2 sub-suites, subsuite_1 and subsuite_2 which had 2 tests and
4 asserts each, the output would be:

Running "Suite_A" (4 tests):
Completed "subsuite_1": 4 passes in Xms.
Completed "subsuite_2": 8 passes in Yms.
Completed "Suite_A": 8 passes in Zms.

This is misleading if you don't realize the count is cumulative.  Since the
"Running" message only occurs for the top-level suite, it makes sense for
the summary to only report for the top-level suite, and is less confusing.
The new output is:

Running "Suite_A" (4 tests):
Completed "Suite_A": 8 passes in Zms.

### CODE REVIEW

**Comment by thoni56** [comment]
What is your primary issue here, the "confusing" counting, or the "extra" lines for sub-suites? Personally I think having the "extra" lines is nice feedback, although they are not balanced (or indented as someone else wanted). I've been thinking about changing the counting to only include the number of tests in the sub-suite...

Could we rephrase the sub-suite lines? Make them only show in the verbose mode, maybe we need multiple levels of verboseness?

**Comment by tboese** [comment]
I have two main concerns:
1)  The number on all sub-suites except the first one is misleading (ie: sub-suite 2 does not have 8 passes, it has 4).  Even worse is when there are failures, as the failures carrying through can mislead you to thinking some sub-suites have failures when they don't.
2)  If we change the sub-suite results, what number do you report on the top-level if it contains both sub-suites and it's own tests?  Is it the total number of passes/failures/etc, or just the results from it's direct tests?

Personally, I like the idea of showing the sub-suite results only in verbose mode would be good.  In this case, I'd still like to change it so that said sub-suite results show only the results from that specific subsuite, but the top-level show totals (in case of not running in verbose).  I'm just not sure how difficult that is when passing a single reporter through all the sub-suites.  I also like the idea of making some visual indicator to separate sub-suites from the total.

**Comment by thoni56** [comment]
I agree with most things. So we'd like an outer "Running/Completed" which would report the total numbers, and an indented(?) set of "Running(?)/Completed" for each sub-suite reporting only its own numbers.

As you say, what would the outer-most suite report? We might consider adding a "pseudo-suite" which would be the textreporter's own "meta-wrapper", in which case that should report the total and will never have any tests of its own.

To make this happen the reporter need to propagate either the suites own numbers or add them to a common totallying structure. I haven't looked into this but am sure that could be made to work. Possible requiring a change to the suite/reporter API which I have no problem with.

**Comment by thoni56** [comment]
What we really would like is then something like:

    Running <pseudosuite>
        <suite1>: 4 passes in 4 ms
        <suite2>: 2 passes, 1 failure in 125ms
    Completed <pseudosuite>: 6 passes, 1 failure in 156ms

For `cgreen-runner` "pseudosuite" could be the basename of the shared library. And if it was given multiple libraries with tests it would repeat the above output for each of those.

Haven't thought about how a "bare" text reporter would/could/should handle the pseudosuite yet...

**Comment by tboese** [comment]
I have a work-in-progress that is reporting this:

Running "Main Suite" (346 tests)...
  Subsuite "subsuite_1": 1 pass in 20ms.
  Subsuite "subsuite_2": 153 passes in 286ms.
  Subsuite "subsuite_3": 55 passes in 37ms.
  Subsuite "subsuite_4": 221 passes in 391ms.
  Subsuite "subsuite_5": 713 passes in 1424ms.
  Subsuite "subsuite_6": 656 passes in 1482ms.
  Subsuite "subsuite_7": 77 passes in 157ms.
  Subsuite "subsuite_8": 224 passes in 452ms.
  Subsuite "subsuite_9": 44 passes in 87ms.
  Top-level-suite "Main Suite": No tests.
Completed "Main Suite": 2144 passes in 4336ms.

I tweaked a lot, including the way time is recorded, so I'm not ready to submit this yet, but I'd like some feedback on the output.  It also works if the Top-level-suite has tests as well as sub-suites (it would give a number and a time instead of "No tests").

**Comment by thoni56** [comment]
Excellent! More or less what I imagined!

If we could leave out the "Top-level-suite: No tests" if the suite did not have any tests of its own, I think that's pretty much it. Perhaps you could also lose the "Subsuite" leading text for the sub-suites? Then the top level, if it contained tests, would just say "Main Suite":

    Running "Main Suite" (346 tests)...
        "subsuite_1": 1 pass in 20ms.
        "subsuite_2": 153 passes in 286ms.
        "subsuite_3": 55 passes in 37ms.
        "subsuite_4": 221 passes in 391ms.
        "subsuite_5": 713 passes in 1424ms.
        "subsuite_6": 656 passes in 1482ms.
        "subsuite_7": 77 passes in 157ms.
        "subsuite_8": 224 passes in 452ms.
        "subsuite_9": 44 passes in 87ms.
        "Main Suite": 13 passes in 128ms.
    Completed "Main Suite": 2144 passes in 4336ms.

Have you considered both the `cgreen-runner` case and the main program runner case? I'm sure we can tweak the other if not, so please proceed anyway, as this looks promising.

**Comment by tboese** [comment]
I am going to disagree on omitting the top-level suite if it had no tests, because I want to treat the top-level suite and sub-suites the same.  In the case of a sub-suite, I like being explicit if there are no tests, as no output at all is confusing (did I miss adding any tests to the suite, or did I omit the suite from my top-level, or did something else go wrong and it just didn't run and report)?  I there could be similar confusion on the pseudo-suite, so I like being  explicit.

I'm happy to omit the pseudo-suite if that is what is desired, I just wanted to make sure this situation was considered.  Also, if omitting the pseudo-suite, should I still include sub-suites with no tests in the report, or should they be omitted as well?

**Comment by thoni56** [comment]
Looks good! As far as I can see the "top-level" has no extra line in the output from `cgreen-runner`. From `make unit`:

    Running "cygcgreen_c_tests" (164 tests)...
      "Mocks": 59 passes in 854ms.
      "ReflectiveNoTeardownTest": 2 passes in 65ms.
      "ReflectiveRunner": 2 passes in 65ms.
      "default": 115 passes in 2219ms.
      "Constraint": 20 passes in 435ms.
      "Breadcrumb": 8 passes in 278ms.
      "Vector": 23 passes in 484ms.
      "MessageFormatting": 2 passes in 40ms.
      "Unittests": 3 passes in 98ms.
      "EnvironmentVariables": 1 pass in 37ms.
      "XmlReporter": 13 passes in 197ms.
      "TextReporter": 7 passes in 130ms.
      "CuteReporter": 15 passes in 106ms.
      "CDashReporter": 10 passes in 177ms.
    Completed "cygcgreen_c_tests": 280 passes in 5185ms.

So that is at least like I wanted it ;-)

**Comment by tboese** [comment]
After running a few more tests against my own project I decided I do like omitting the top level if it doesn't have any independent tests, so that is what is in the PR currently.  If a bottom-level suite has no tests, then it does print "No tests."

**Comment by thoni56** [comment]
Perfect! Let me know when you feel its ok to merge.

**Comment by tboese** [comment]
I think it's good now, if it looks good to you as well :)

**Comment by thoni56** [comment]
Thank you @tboese! An excellent addition!

**Pull request merged**
