### PR TITLE
[issue #4] add almost-working implementation for more double constraints

### PR DESCRIPTION
**Pull request by matthargett**
…to better parallel non-double value constraints.

My new-dad brain can't wrap itself around the finer details of float comparison, so help on those double_is_greater and double_is_lesser functions in assertions.c would be appreciated.

### CODE REVIEW

**Comment by d-meiser** [comment]
Just to make sure I understand: The tests you currently have are all passing but you're not sure if there are some cases were the constraints might fail?

FWIW whenever I've needed `<` or `>` for floating point numbers in the past I've used these without specifying the number of significant digits. Perhaps using plain `<` and `>` is good enough? That's what `boost::unit_test` and `gtest` do as well. A benefit of this is that test failures are easier to interpret for users of the library.

**Comment by matthargett** [comment]
correct. I did get it to work, but don't understand why it works. The significant digits thing needs to work consistently across all the double constraints -- that feature is there because a few teams needed it.

**Comment by d-meiser** [comment]
I see. I'll have a look at it.

**Comment by d-meiser** [comment]
@matthargett I opened a pull request to your branch. If you accept it this pull request should get updated automatically with the fixes.

**Comment by d-meiser** [comment]
While working on this I thought it might make sense to have a mechanism for an infinite number of significant digits. This is less useful when testing for equality for floating point numbers but for "greater than"/"less than" tests it makes sense.

I think it could be added rather easily added to the current code. We could interpret negative numbers of `significant_figures` as infinity. In that case `accuracy` should return `0`.

**Comment by d-meiser** [comment]
I should point out that there is an issue with `test_all_constraints`. I'm getting the following output

```
Completed "all_constraints_tests": 1 pass, 30 failures, 1 exception.
Completed "main": 1 pass, 30 failures, 1 exception.
```
I.e. there is one pass when there should be only failures. I haven't had a chance to look into this yet. I hope to get to it tonight.

**Comment by d-meiser** [comment]
I fixed the logic error mentioned in the previous comment. Opened a pull request to @matthargett's branch.

**Comment by thoni56** [comment]
Nice. So the newly added tests did immediate goodness!

**Comment by thoni56** [comment]
So we're waiting for @matthargett to pull up @d-meiser:s changes first.

**Comment by d-meiser** [comment]
Yes. Regarding the conflict pointed out by github: These are due to changes in the documentation and should be rather easy to resolve. Do you want to resolve them during merge or should this branch be rebased onto current master and the conflict resolved during that process?

**Comment by thoni56** [comment]
I can take care of the conflicts.

**Comment by d-meiser** [comment]
Note that this pull request will  also require that the expected output from the `test_all_constraints` executable be adjusted. Because there are so many moving pieces (@mattgargett`s changes, my patch, and the modification of the test output) I propose that we merge into a new branch for integration rather than directly into master. We can then sort out any further issues in the integration branch. Something along the lines of the following workflow:

```
git checkout -b double-constraints-integration
# Merge Matt's branch and resolve the conflict
git merge matthargett-upstream/master
vim doc/cgreen-guide-en.asciidoc
git commit -a
# Apply d-meiser's patch
git merge d-meiser-upstream/less-than-double
# Fix expected output from test_all_constraints
# Push to github and open pull request
```

**Comment by thoni56** [comment]
That's probably a good plan. I'll see if I can start on that tonight.

**Comment by thoni56** [comment]
Thanks, @d-meiser for helping out with this, including the workflow hints! Turned out nice.

**Comment by d-meiser** [comment]
Nice, glad it all worked out.

**Pull request merged**
